In [2]:
import numpy as np

In [6]:
arr1 = np.arange(2)
print("一维数组:\n",arr1)
arr2 = np.arange(4).reshape(2,2)
print("二维数组:\n",arr2)
arr3 = np.arange(8).reshape(2,2,2)
print("三维数组:\n",arr3)
print(type(arr1),type(arr2),type(arr3))

一维数组:
 [0 1]
二维数组:
 [[0 1]
 [2 3]]
三维数组:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [7]:
a=[1,3,5,7]
arr =np.array(a)
print(arr,type(arr))

[1 3 5 7] <class 'numpy.ndarray'>


In [8]:
arr1 = np.arange(10)
print(arr1,type(arr1))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [9]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
print("一维数组：\n",np.ones(3))
print("二维数组：\n",np.ones([3,4]))

一维数组：
 [1. 1. 1.]
二维数组：
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
print(np.random.rand(20))
print(np.random.randint(0,10,20))

[0.44130882 0.20424948 0.99042929 0.01036702 0.08519083 0.42657109
 0.56075958 0.75855092 0.77276715 0.68893574 0.77338052 0.5255678
 0.25253334 0.14031995 0.47320634 0.66343966 0.67920627 0.3684717
 0.35333774 0.28467415]
[5 5 5 6 7 1 1 5 8 1 5 1 4 9 5 0 6 8 8 9]


In [15]:
print("2X2的单位矩阵：\n",np.identity(2))
print("3X3的单位矩阵：\n",np.identity(3))

2X2的单位矩阵：
 [[1. 0.]
 [0. 1.]]
3X3的单位矩阵：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
arr = np.ones([3,4])
print("维度数：",arr.ndim)
print("形状：",arr.shape)
print("元素数：",arr.size)

维度数： 2
形状： (3, 4)
元素数： 12


In [17]:
arr = np.arange(12)
print("arr:",arr)
print("第二个元素：",arr[1])
print("第十一个元素：",arr[10])

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
第二个元素： 1
第十一个元素： 10


In [23]:
arr0 = np.arange(12).reshape(3,4)
print("arr0: \n",arr0)
print("第一维第三个，第二维第四个元素：",arr0[2,3])
print("\n")
arr1 = np.arange(12).reshape(2,2,3)
print("arr1:",arr1)
print("第一维第二个，第二维第一个，第三维第三个数：",arr1[1,0,2])

arr0: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
第一维第三个，第二维第四个元素： 11


arr1: [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
第一维第二个，第二维第一个，第三维第三个数： 8


In [24]:
arr = np.arange(12).reshape(2,6)
print("原始二维数组：\n",arr)
print("提供一个索引后，得到一维数组：\n",arr[0])

原始二维数组：
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
提供一个索引后，得到一维数组：
 [0 1 2 3 4 5]


In [25]:
arr = np.arange(10)
print("arr:\n",arr)
print("从索引2到索引4：",arr[2:4])
print("从索引1到索引5：",arr[1:5])

arr:
 [0 1 2 3 4 5 6 7 8 9]
从索引2到索引4： [2 3]
从索引1到索引5： [1 2 3 4]


In [26]:
arr = np.arange(9).reshape(3,3)
print("arr:\n",arr)
print(arr[1:3,0])

arr:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 6]


In [27]:
arr = np.arange(12).reshape(3,4)
print("原始数组：\n",arr)
print("数组+2：\n",arr+2)
print("数组*2：\n",arr*2)
print("数组/2：\n",arr/2)

原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组+2：
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
数组*2：
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
数组/2：
 [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [40]:
arr = np.arange(12).reshape(3,4)
arr1 = np.random.randint(1,20,[3,4])
print("原始数组1：\n",arr)
print("原始数组2：\n",arr1)
print("数组相加的结果：\n",arr+arr1)
print("数组相乘的结果：\n",arr*arr1)

原始数组1：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原始数组2：
 [[11  6 12  2]
 [ 5  3  1 16]
 [ 2  2 16 12]]
数组相加的结果：
 [[11  7 14  5]
 [ 9  8  7 23]
 [10 11 26 23]]
数组相乘的结果：
 [[  0   6  24   6]
 [ 20  15   6 112]
 [ 16  18 160 132]]


In [41]:
arr = np.arange(12).reshape(3,4)
arr1 = np.arange(4)
print("原始数组1：\n",arr)
print("原始数组2：\n",arr1)
print("数组相加的结果：\n",arr+arr1)
print("数组相乘的结果：\n",arr*arr1)

原始数组1：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原始数组2：
 [0 1 2 3]
数组相加的结果：
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
数组相乘的结果：
 [[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]


In [42]:
arr = np.arange(12).reshape(3,4)
print("原始数组：\n",arr)
print("求平方：\n",np.square(arr))
print("开根：\n",np.sqrt(arr))
print("正弦函数：\n",np.sin(arr))

原始数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
求平方：
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
开根：
 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
正弦函数：
 [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [44]:
arr = np.arange(4)
arr1= np.arange(2,6)
print("原始数组1：\n",arr)
print("原始数组2：\n",arr1)
print("不允许误差:",np.allclose(arr,arr1))
print("允许误差1：",np.allclose(arr,arr1,atol=1))
print("允许误差2：",np.allclose(arr,arr1,atol=2))

原始数组1：
 [0 1 2 3]
原始数组2：
 [2 3 4 5]
不允许误差: False
允许误差1： False
允许误差2： True


首先，我们学习了 NumPy 中的多维数组：ndarray 以及基本概念。

然后我们学习了 ndarray 的基本创建，主要有以下的形式。

通过现有列表创建：np.array

生成一个连续元素的数组：np.arange

重新调整数组的形状：reshape

全 0：np.zeros

全 1：np.ones

随机数：np.random.rand

之后是 ndarray 的索引方式。

一维数组元素索引：[index]

多维数组元素索引：[index1, index2, ... indexN]

范围索引：[开始索引 : 结束索引]

最后，我们学习了 ndarray 的计算规则。

单一元素与数组计算：将元素和数组的每个元素分别计算并返回数组

数组与数组的计算：形状一致的数组对应位置的元素分别计算

对数组应用数学函数：对每一个元素应用数学函数，并返回同样形状的数组

计算两个数组是否接近：allclose 函数

下一讲，我们将会介绍基于 NumPy 的常见的统计分析方法。

In [46]:
# 如下面的代码所示，列表 a 中存储了学生小 A 的各科成绩，列表 b 中存储了学生小 B 的各科成绩，是 150 分制。要求:

# 将两人的成绩都转换为百分制，并打印；

# 如果各科分数差 10 分以内，则认为水平相近，计算小 A 和小 B 的水平是否相近，并打印。

# a = [100, 122, 123,  94, 147]
# b = [ 94, 120,  131, 103, 140]

a = [100,122,123,94,147]
b = [94,120,131,103,140]
arr_a = np.array(a)
arr_b= np.array(b)
arr_a = arr_a *100/150
arr_b = arr_b *100/150
print("小A的百分制成绩",arr_a)
print("小B的百分制成绩",arr_b)
print("小A和小B的水平是否相近:",np.allclose(arr_a,arr_b,atol=10))

小A的百分制成绩 [66.66666667 81.33333333 82.         62.66666667 98.        ]
小B的百分制成绩 [62.66666667 80.         87.33333333 68.66666667 93.33333333]
小A和小B的水平是否相近: True
